### ISSUE TITLE
Proposal: data plane design

### ISSUE THREAD

**Issue by tamalsaha** [kube-ci/project#2]
_From @tamalsaha on July 18, 2018 11:53_

```
 m1        |    m2              | m3
--------------------------------------------


Repository r1

- Assign to machine mX
- mX (locally) producer
 - clone repo,
 - refresh every N secs for updated branch, pull request, commit
 - When it finds a new / updated Resource (B/P/C), it writes to central data plane

--------------------------------------------

Git Branch Registry

Watch interface {
}

// consumer of data plane
go func() {
	lastObservedGeneration_of_resource := __
	tick.func() {
		switch{
			<- stop():
			 return
			<- wait_for_read():
				latest := Get lasted generator for branch from central data plane,
				if latest > lastObservedGeneration_of_resource {
					<- resultChan
					lastObservedGeneration_of_resource = latest
				}
		}
	}
}
```

_Copied from original issue: kube-ci/git-apiserver#3_

**Comment by tamalsaha** [comment]
Leader Election
- https://github.com/appscode/kutil/issues/184


```
apiVersion: git.kube.ci
kind: Repository
spec:
  url: https://github.com/appscode/voyage.git
status:

----------

----------
apiVersion: git.kube.ci
kind: RepositoryBinding
metadata:
  name: repo-name
  labels:
    node: <node-name>
status:
  lastSynced:
  size: n MB


 - node=$(ENV_VAR_NAME)

```
